# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.menu_builder:
        class: AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@security.authorization_checker"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }

    app.datatable.user:
        class: MGD\UserBundle\Datatables\UserDatatable
        parent: sg_datatables.datatable.abstract