<?php

namespace MGD\EventBundle\Repository;

/**
 * DiscoveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscoveryRepository extends \Doctrine\ORM\EntityRepository
{
}
