<?php

namespace MGD\EventBundle\Repository;

/**
 * UserGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamingProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
