<?php

namespace MGD\EventBundle\Repository;

/**
 * TournamentTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
