<?php

namespace MGD\EventBundle\Repository;

/**
 * TournamentSoloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentSoloRepository extends \Doctrine\ORM\EntityRepository
{
}
