mdg_tournament_view:
    path:    /tournament/{id}
    defaults: { _controller: MGDEventBundle:Tournament:view }
    requirements:
        id:    \d*
    methods:   ["GET"]

mgd_tournament_apply:
    path:    /tournament/apply/{id}
    defaults: { _controller: MGDEventBundle:Tournament:apply}
    requirements:
        id:    \d*
    methods:   ["GET"]

mgd_tournament_quit:
    path:    /tournament/quit/{id}
    defaults: { _controller: MGDEventBundle:Tournament:quit}
    requirements:
        id:    \d*
    methods:   ["GET"]

mdg_discovery_view:
    path:    /discovery/{id}
    defaults: { _controller: MGDEventBundle:Discovery:view }
    requirements:
        id:    \d*
    methods:   ["GET"]

mgd_event_homepage:
    path:     /
    defaults: { _controller: MGDEventBundle:Default:index }
    methods:   ["GET"]

mgd_team_show:
    path:     /team/{id}/show
    defaults: { _controller: "MGDEventBundle:Team:show" }
    methods:  GET

mgd_team_new:
    path:     /team/new/{id}
    defaults: { _controller: "MGDEventBundle:Team:new" }
    methods:  [GET, POST]

mgd_team_edit:
    path:     /team/{id}/edit
    defaults: { _controller: "MGDEventBundle:Team:edit" }
    methods:  [GET, POST]

mgd_team_delete:
    path:     /team/{id}/delete
    defaults: { _controller: "MGDEventBundle:Team:delete" }
    methods:  DELETE

mgd_team_application:
    path:     /team/{id}/application
    defaults: { _controller: "MGDEventBundle:Team:application" }
    methods:  POST

mgd_team_quit:
    path:    /team/{id}/quit
    defaults: { _controller: "MGDEventBundle:Team:quit"}
    methods:  POST
