services:
    mgd_event.route_generator:
        class:     MGD\EventBundle\Twig\AppExtension
        public:    false
        arguments: ["@router"]
        tags:
            - { name: twig.extension }

#    mgd_event.example:
#        class: MGD\EventBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
