<?php

namespace MGD\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getApplicant($team)
    {
        return $this->createQueryBuilder("user")
            ->leftJoin("user.applications", "applications")
            ->where("applications = :team")
            ->setParameter("team", $team);
    }
}
